apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: simple-nginx
        image: maltekreeti/simple-nginx:v2
        ports:
        - containerPort: 8080
