apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-svc
spec:
  type: ClusterIP      
  ports:
  - port: 80
    containerPort: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: simple-nginx
    deployment: ${DEPLOYMENT}
