apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-svc
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80  
    nodePort: 30007
  selector:
    app: simple-nginx
    deployment: ${DEPLOYMENT}
